spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    animeservice: debug

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on-param
  tomcat:
    threads:
      max: 20

database:
  url: ${DB_URL:localhost}:${DB_PORT:3306}
  username: ${LOCAL_USERNAME:rafael}
  password: ${LOCAL_PASSWORD:rafael123}
